<?php

// $Id: cck_signup_group.module,v 1.5 2010/07/26 23:41:06 jhedstrom Exp $

/**
 * @file
 * Sign-up functionality for groups.
 */

/**
 * Implementation of hook_cck_signup_validate().
 */
function cck_signup_group_cck_signup_validate($type, $event, &$form_state) {
  if (variable_get('cck_signup_group_type_' . $type, FALSE) && $field = variable_get('cck_signup_group_field_count_' . $type, FALSE)) {
    $values = $form_state['values'];
    if ($check_limit = variable_get('cck_signup_field_capacity_' . $event->type, FALSE)) {
      // Sign-up count cannot exceed the event capacity.
      $count = $values[$field][0]['value'];
      if (empty($count)) {
        // CCK should catch this error.
      }
      else {
        // Need to account for updating the number of signups
        $old_count = 0;
        if ($values['nid']) {
          $old = node_load($values['nid']);
          $old_count = $old->{$field}[0]['value'];
        }
        $limit = $event->{$check_limit}[0]['value'];
        $remaining = cck_signup_get_remaining_capacity($event);
        if (($count - $old_count) > $remaining && !user_access('override cck signup restrictions')) {
          form_set_error($field, t('There are only %remaining slots open for %title.', array('%remaining' => $remaining, '%title' => $event->title)));
        }
      }
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function cck_signup_group_form_alter(&$form, $form_state, $form_id) {
  if (!empty($form['type']['#value'])) {
    if ($form_id == $form['type']['#value'] .'_node_form'
      && variable_get('cck_signup_group_type_' . $form['type']['#value'], FALSE)) {
      $field = variable_get('cck_signup_group_field_count_' . $form['type']['#value'], '');
      $group = variable_get('cck_signup_group_fieldgroup_' . $form['type']['#value'], FALSE);

      if ($field && $group) {
        $settings = array(
          'field' => str_replace('_', '-', $field),
          'group' => str_replace('_', '-', $group),
        );
        drupal_add_js(array('cckSignupGroup' => $settings), 'setting');
        drupal_add_js(drupal_get_path('module', 'cck_signup_group') . '/cck-signup-group.js');
      }
    }
  }
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function cck_signup_group_form_node_type_form_alter(&$form, $form_state) {
  module_load_include('admin.inc', 'cck_signup_group');
  _cck_signup_group_form_node_type_form_alter($form, $form_state);
}

/**
 * Implementation of hook_cck_signup_available_capacity_alter().
 */
function cck_signup_group_cck_signup_available_capacity_alter(&$signups, $event) {
  $signup_field = variable_get('cck_signup_field_' . $event->type, FALSE);
  foreach ($signups as $type => $count) {
    if (variable_get('cck_signup_group_type_' . $type, FALSE) && $field = variable_get('cck_signup_group_field_count_' . $type, FALSE)) {
      // Since this is a group signup, the $count passed here only
      // reflects the number of group signups. This needs to be turned into the
      // actual number signup up in each record.
      $db_info_count = content_database_info(content_fields($field));
      $db_info_signup = content_database_info(content_fields($signup_field));
      $real_count = db_result(
        db_query("
          SELECT SUM(gc.%s) 
          FROM {node} 
          LEFT JOIN {%s} gc USING (vid)
          LEFT JOIN {%s} sn USING (vid) WHERE node.type = '%s' AND sn.%s = %d",
          array(
            ':count_column' => $db_info_count['columns']['value']['column'],
            ':count_table' => $db_info_count['table'],
            ':signup_table' => $db_info_signup['table'],
            ':type' => $type,
            ':signup_column' => $db_info_signup['columns']['nid']['column'],
            ':nid' => $event->nid,
          )));
      $signups[$type] = $real_count;
    }
  }
}


/**
 * Determine if a given sign-up node is a group sign-up (defined by having a count of more than 1).
 *
 * @param $signup
 *   A sign-up node object.
 * @return boolean
 */
function cck_signup_group_is_group_signup($signup) {
  // Get the count field.
  $group_count_field = variable_get('cck_signup_group_field_count_' . $signup->type, FALSE);
  return $group_count_field
    && isset($signup->{$group_count_field})
    && ($signup->{$group_count_field}[0]['value'] > 1);
}
